# Generated by Django 2.0.2 on 2018-02-06 22:35

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('excerpt', markupfield.fields.MarkupField(rendered_field=True, verbose_name='Excerpt from a book')),
                ('excerpt_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default='html', max_length=30)),
                ('url_link', models.URLField()),
                ('_excerpt_rendered', models.TextField(editable=False)),
            ],
        ),
    ]
