# Generated by Django 2.0.2 on 2018-02-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_covers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='_excerpt_rendered',
        ),
        migrations.RemoveField(
            model_name='book',
            name='excerpt_markup_type',
        ),
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=models.TextField(max_length=2000, verbose_name='Excerpt from a book'),
        ),
    ]
