# Generated by Django 2.0.2 on 2018-02-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_covers', '0002_auto_20180210_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='resource',
            field=models.CharField(default='None', max_length=100, verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=models.TextField(verbose_name='Excerpt from a book'),
        ),
    ]
