# Generated by Django 2.0.2 on 2018-02-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_covers', '0003_auto_20180211_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='resource',
            field=models.CharField(max_length=100, verbose_name='Resource'),
        ),
    ]
